version: "3.5"

services:
  sonarqube:
    image: sonarqube:community
    platform: linux/x86_64
    depends_on:
      - init
      - db
    environment:
      - SONAR_JDBC_USERNAME=sonar # usuário default: admin
      - SONAR_JDBC_PASSWORD=sonar # senha default: sonar
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - sonar.search.javaAdditionalOpts="-Dnode.store.allow_mmap=false"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
  init:
    image: bash
    privileged: true
    user: root
    volumes:
      - ~/Projects/Docker/sonarqube/init.sh:/mnt/init.sh
    command: [ "sh", "-e", "/mnt/init.sh" ]

  db:
    image: postgres:13
    platform: linux/x86_64
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - sonarnet

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:

networks:
  sonarnet:

# SOBRE O COMANDO: sonar.search.javaAdditionalOpts="-Dnode.store.allow_mmap=false"

# O parâmetro -Dnode.store.allow_mmap=false é uma configuração específica para o SonarQube quando ele é executado com o banco de dados Elasticsearch.
# Essa configuração é usada para desabilitar o uso de mapeamento de memória para o armazenamento de nós (nodes) no Elasticsearch.

# Ao utilizar o Elasticsearch como mecanismo de indexação e busca no SonarQube, o parâmetro -Dnode.store.allow_mmap=false pode ser passado para a JVM (Java Virtual Machine)
# como uma opção para desabilitar o uso de mmap (mapeamento de memória) para o armazenamento de nós do Elasticsearch.

# O mmap é uma técnica de otimização que permite mapear um arquivo no espaço de endereço de um processo e acessá-lo diretamente da memória.
# No entanto, em certos ambientes ou sistemas de arquivos, o uso do mmap pode causar problemas de desempenho ou estabilidade.
